/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as FundadorRouteImport } from './routes/fundador'
import { Route as MetodologiaRouteImport } from './routes/metodologia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FundadorRoute = FundadorRouteImport.update({
  id: '/fundador',
  path: '/fundador',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depoimentos': typeof DepoimentosRoute
  '/fundador': typeof FundadorRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depoimentos': typeof DepoimentosRoute
  '/fundador': typeof FundadorRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depoimentos': typeof DepoimentosRoute
  '/fundador': typeof FundadorRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/depoimentos' | '/fundador' | '/metodologia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/depoimentos' | '/fundador' | '/metodologia'
  id: '__root__' | '/' | '/depoimentos' | '/fundador' | '/metodologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepoimentosRoute: typeof DepoimentosRoute
  FundadorRoute: typeof FundadorRoute
  MetodologiaRoute: typeof MetodologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundador': {
      id: '/fundador'
      path: '/fundador'
      fullPath: '/fundador'
      preLoaderRoute: typeof FundadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepoimentosRoute: DepoimentosRoute,
  FundadorRoute: FundadorRoute,
  MetodologiaRoute: MetodologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
